In [24]:
import numpy as np
import sympy as sy
from numpy import linalg as LA


In [7]:
A = np.random.rand(10, 4)

In [16]:
Q = np.matmul(np.transpose(A), A)
def calculate(x, Q):
    xTx = np.matmul(np.transpose(x), x)
    f_x = np.matmul(np.matmul(np.transpose(x), Q), x)/xTx
    nabla_f = (2*x*f_x)/xTx - (np.matmul(2*Q, x))/xTx
    return f_x, nabla_f

In [18]:
f, g = calculate(np.array([1,1,1,1]), Q)

In [25]:
LA.eig(Q)

(array([7.35388927, 1.23965652, 0.5852192 , 0.45927148]),
 array([[ 0.50270537,  0.6061651 ,  0.48382788,  0.3817876 ],
        [ 0.4973109 ,  0.37748792, -0.55953338, -0.54507535],
        [ 0.44936846, -0.49731651,  0.5496386 , -0.49863984],
        [ 0.5459278 , -0.4926896 , -0.38824012,  0.55541823]]))

array([-0.02765815,  0.01451101,  0.33612695, -0.32297982])